[build]
  command = "yarn build"
  publish = "out"

[[plugins]]
package = "netlify-plugin-cache-nextjs"

[context.production.environment]
  NEXT_PUBLIC_LICENSESERVER_URL = "https://us-central1-kubernetic-e81de.cloudfunctions.net/httpsStripeSession"
  NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY = "pk_live_STtPmOIz0ofohsd3WqPKB4Lo00f5xOj2iB"

[context.staging.environment]
  NEXT_PUBLIC_LICENSESERVER_URL = "https://us-central1-kubernetic-test.cloudfunctions.net/httpsStripeSession"
  NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY = "pk_test_T7mLNhEI2PjHP95pAVXjTmKz00n4zAWGQ3"

[context.branch-deploy.environment]
  NEXT_PUBLIC_LICENSESERVER_URL = "https://us-central1-kubernetic-test.cloudfunctions.net/httpsStripeSession"
  NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY = "pk_test_T7mLNhEI2PjHP95pAVXjTmKz00n4zAWGQ3"
